- name: Build and run Docker container
  hosts: docker
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: true

    - name: Build Docker image
      command: docker build -t ABC-App

    - name: Run Docker container
      command: docker run -d -p 8080:8080 --name ABC-App

